### ISSUE TITLE
Criar esqueleto da tela de membros

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#10]
## **Descrição da nova funcionalidade**
Criar o esqueleto da tela onde serão mostrados os membros da empresa.

#### Tela membros
![Membros](https://user-images.githubusercontent.com/54643355/67619007-b98e2380-f7cc-11e9-9bec-a37cd17caa00.png)

Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A601
#### Funcionalidade
![NavBar](https://user-images.githubusercontent.com/54643355/67619009-beeb6e00-f7cc-11e9-83ab-e268925c1a03.png)

Link da funcionalidade: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A601

### **Rota da api**
Não é necessário

### **Tasks da funcionalidade**
- [x] Criar tela inicial vazia;
- [x] Pegar ícone da Orc'estra;
- [x] Criar barra superior.

### **Critérios de Aceitação**
- [x] Posicionar itens de acordo com o protótipo;
- [x] Utilizar identidade visual do protótipo(fonte e cores).
