### ISSUE TITLE
Criar esqueleto da tela de perfil

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#11]
## **Descrição da nova funcionalidade**
Criar esqueleto da tela onde serão exibidos as informações do usuário

#### Tela de Perfil
![Perfil](https://user-images.githubusercontent.com/46005310/67406573-9ffe9900-f58c-11e9-8ebe-fb5b53a721f4.png)
Link para tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A647
#### Funcionalidade
![Barra topo (5)](https://user-images.githubusercontent.com/46005310/67406634-b0167880-f58c-11e9-968f-c4f1f27265f7.png)
Link para tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A647

### **Rota da api**
Não é necessário
### **Tasks da funcionalidade**
- [ ] Criar tela inicial vazia;
- [ ] Pegar ícone da Orc'estra;
- [ ] Criar barra superior.

### **Critérios de Aceitação**
- [ ] Posicionar itens de acordo com o protótipo;
- [ ] Utilizar identidade visual do protótipo(fonte e cores).
