### ISSUE TITLE
Criar a barra de navegação inferior

### ISSUE THREAD

**Issue by alan-ms** [OrcestraGamificacao/portalOrcApp#12]
## **Descrição da nova funcionalidade**
Criar a barra de navegação inferior no arquivo de **routes**. Leiam o artigo da rocketseat sobre o tipos de navegação para ter uma noção de como fazer. 
Site: https://blog.rocketseat.com.br/navegacao-react-native/ 

### **Print da tela do Protótipo**
![Screenshot from 2019-10-23 09-33-29](https://user-images.githubusercontent.com/35638067/67409777-6714f300-f591-11e9-804e-d31bc50a350d.png)

### **Rota da api**
Não há rota para a API..

### **Tasks da funcionalidade**
- [x] Criar a barra de navegação na parte inferior
- [x] Usar os ícones da biblioteca **react-native-vector-icons**, que já foi adicionada no projeto
- [x] Deixar comentado as rotas das telas que ainda não estão prontas

### **Critérios de Aceitação**
- [ ] Criar as rotas, deixando comentado as rotas que a tela ainda não está pronta
- [ ] Posicionar as rotas de acordo com o protótipo
