### ISSUE TITLE
Mostrar atividades na tela de atividades

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#13]
## **Descrição da nova funcionalidade**
Mostrar todas as atividades feitas na tela de atividades.

#### Tela
![Atividades (1)](https://user-images.githubusercontent.com/46005310/67409911-a0e5f980-f591-11e9-8791-2e18202f58bd.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A217

### **Rota da api**
```
```

### **Tasks da funcionalidade**
- [ ] Utilizar a api para pegar todos os membros da organização;
- [ ] Pegar informações dos membros;
- [ ] Mostrar nome e diretoria tela.
### **Critérios de Aceitação**
- [ ] Mostrar todos os membros da organização;
- [ ] Ter foto, nome e suas respectivas diretorias.
