### ISSUE TITLE
Mostrar todos os membros na tela de membros

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#14]
## **Descrição da nova funcionalidade**
Mostrar todos os membros da organização na tela de membros.

#### Tela
![Membros (1)](https://user-images.githubusercontent.com/46005310/67410953-3e8df880-f593-11e9-9d73-25f09577b952.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A601

### **Rota da api**
```
```
### **Tasks da funcionalidade**
- [ ] Utilizar a api para pegar todos os membros da organização;
- [ ] Pegar informações dos membros;
- [ ] Mostrar nome e diretoria tela.
### **Critérios de Aceitação**
- [ ] Mostrar todos os membros da organização;
- [ ] Ter foto, nome e suas respectivas diretorias.
