### ISSUE TITLE
Filtrar dados da tela de atividades

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#15]
## **Descrição da nova funcionalidade**
Filtrar os dados mostrados na tela de atividades em **hoje**, **esta semana** e **este mês**

### **Print da tela do Protótipo**
![Atividades (1)](https://user-images.githubusercontent.com/46005310/67412953-a6920e00-f596-11e9-8768-eaa9fe6f9d98.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A217
### **Rota da api**
```
```

### **Tasks da funcionalidade**
- [ ] Ver na api a data de criação/atualização de cada atividade;
- [ ] Criar um filtro para mostrar as atividades do dia de hoje;
- [ ] Criar um filtro para mostrar as atividades dessa semana;
- [ ] Criar um filtro para mostrar as atividades desse mês.
### **Critérios de Aceitação**
- [ ] Seguir protótipo;
- [ ] Mostrar todas as atividades filtradas na mesma página.
