### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by lucianaribeiro** [OrcestraGamificacao/portalOrcApp#16]
## **Descrição da nova funcionalidade**
Criar tela para que o usuário possa acessar o aplicativo 

### **Print da tela do Protótipo**
![Membros](https://user-images.githubusercontent.com/23436276/67414102-caeeea00-f598-11e9-8fd8-5f3d8e18e363.png)

https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A1297

### **Rota da api**
Por enquanto não deve se conectar com a API

### **Tasks da funcionalidade**
- [ ] Colocar fundo verde
- [ ] Colocar logo da Orc'estra
- [ ] Criar form de login
- [ ] Colocar botão de entrar  

### **Critérios de Aceitação**
- [ ] Seguir o protótipo
