### ISSUE TITLE
Criar tela de perfil

### ISSUE THREAD

**Issue by alan-ms** [OrcestraGamificacao/portalOrcApp#17]
## **Descrição da nova funcionalidade**
Criação da tela de perfil do usuário com as informações: nome, diretoria, email e avatar.

### **Print da tela do Protótipo**
![Screenshot from 2019-10-23 13-36-59](https://user-images.githubusercontent.com/35638067/67427883-64c39080-f5b3-11e9-89d3-7090d6659ef9.png)

### **Rota da api**
Rota: **/user/status**
https://developers.podio.com/doc/users/get-user-status-22480

### **Tasks da funcionalidade**
- [ ] Exibir o avatar do usuário do Podio
- [ ] Exibir diretoria do usuário
- [ ] Exibir o email do usuário
- [ ] Exibir a diretoria do usuário
- [ ] Apresentar o botão para ir pro calendário
- [ ] Ao clicar em perfil da barra de navegação, o aplicativo deve apresentar a tela de perfil

### **Critérios de Aceitação**
- [ ] Tela de acordo protótipo
- [ ] As informações do usuário devem estar sendo apresentadas de maneira correta
