### ISSUE TITLE
Criar tela de calendário

### ISSUE THREAD

**Issue by MatheusBlanco** [OrcestraGamificacao/portalOrcApp#26]
## **Descrição da nova funcionalidade**
Criar tela de calendário, para que o usuário possa ver os dias do mês, semana, atividades do dia e atividades da semana.

### **Print da tela do Protótipo**

![calendario](https://user-images.githubusercontent.com/37380789/68314719-6605ba80-0095-11ea-9669-64ff111d2656.png)

### **Tasks da funcionalidade**
- [ ] Criar calendario;
- [ ] Aplicar fundo branco;
- [ ] Seção de atividades do dia;
- [ ] Seção de atividades da semana;

### **Critérios de Aceitação**
- [ ] Seguir o protótipo
