### ISSUE TITLE
Tela de tarefas - Criar tela de minhas, delegadas e concluídas

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#27]
## **Descrição da nova funcionalidade**
Criar tabs minhas, delegadas e concluídas e suas linkar com suas respectivas páginas.

#### Tabs minhas, delegadas e concluídas
![Frame 1](https://user-images.githubusercontent.com/46005310/68314548-17582080-0095-11ea-844d-ae9c0051c830.png)
Link para funcionalidade: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=5%3A524

#### Tela de minhas tarefas
![minhas-tarefas](https://user-images.githubusercontent.com/46005310/68314341-c0eae200-0094-11ea-99f9-288168592e89.png)
Link para tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=5%3A524

#### Tela de tarefas delegadas
![tarefas-delegadas](https://user-images.githubusercontent.com/46005310/68314681-571f0800-0095-11ea-890a-063c1b6ea3f5.png)
Link para tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=9%3A153

#### Tela de tarefas concluídas
![tarefas-concluidas](https://user-images.githubusercontent.com/46005310/68314884-b3822780-0095-11ea-9ac7-a6d9fe109c88.png)
Link para tarefa: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=9%3A362

### **Tasks da funcionalidade**
- [ ] Criar navs para cada página;
- [ ] Integrar os botões com as páginas.

### **Critérios de Aceitação**
- [ ] Ser possível navegar entre as telas.
