### ISSUE TITLE
Criar tela de notificações

### ISSUE THREAD

**Issue by MatheusBlanco** [OrcestraGamificacao/portalOrcApp#28]
## **Descrição da nova funcionalidade**
Criar tela de notificações, para visualização das lidas e não lidas

### **Print da tela do Protótipo**
![Notificações](https://user-images.githubusercontent.com/37380789/68315243-3c00c800-0096-11ea-979e-4335cf964e7c.png)

### **Tasks da funcionalidade**
- [ ] Criar uma seção para notificações lidas;
- [ ] Criar uma seção para notificações não lidas;
- [ ] Notificações deverão ter foto do remetente, texto e rota para ver mais;
- [ ] Aplicar fundo branco;

### **Critérios de Aceitação**
- [ ] Seguir o protótipo.
