### ISSUE TITLE
Tela de Tarefas - Criar pop-up de nova tarefa

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#29]
## **Descrição da nova funcionalidade**
Permitir que quando o usuário clicar no botão "+" ser capaz de criar uma nova tarefa, assim como a mostrada no protótipo.
#### Botão "+"
![Barra topo](https://user-images.githubusercontent.com/46005310/68315505-a0bc2280-0096-11ea-91f9-c16dca7519a0.png)
Link: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=9%3A362

#### Pop-up de nova tarefa
![nova-tarefa](https://user-images.githubusercontent.com/46005310/68315602-c8ab8600-0096-11ea-9c8f-295f6962cd57.png)
Link: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=9%3A362

### **Tasks da funcionalidade**
- [ ] Criar pop-up "Nova tarefa";
- [ ] Criar um campo de texto para inserir o nome da tarefa;
- [ ] Criar botão de salvar(não precisa estar funcionando);
- [ ] Criar botão de detalhar(não precisa estar
 funcionando).
### **Critérios de Aceitação**
- [ ] Criar pop-up;
- [ ] Seguiir protótipo;
- [ ] Ser capaz de sair do pop-up clicando na área escuro.
