### ISSUE TITLE
Criar seções de atividade

### ISSUE THREAD

**Issue by MatheusBlanco** [OrcestraGamificacao/portalOrcApp#33]
## **Descrição da nova funcionalidade**
Criar atividades do dia e atividades da semana

### **Print da tela do Protótipo**
![68314719-6605ba80-0095-11ea-9669-64ff111d2656](https://user-images.githubusercontent.com/37380789/68318275-48d3ea80-009b-11ea-9e50-9562d57f5ca8.png)

### **Tasks da funcionalidade**
- [ ] Criar seção de atividades do dia
- [ ] Criar titulo de atividades do dia
- [ ] Criar seção de atividades da semana
- [ ] Criar titulo de atividades da semana

### **Critérios de Aceitação**
- [ ] Seguir o protótipo
