### ISSUE TITLE
Tela de Tarefas - Detalhar tarefa

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#36]
## **Descrição da nova funcionalidade**
Criar tela de detalhar nova taarefa.
#### Tela de detalhar tarefa
![nova-tarefa(1)](https://user-images.githubusercontent.com/46005310/68318466-994b4800-009b-11ea-91e7-c195eb78a3c1.png)
Link para tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/portalOrcApp?node-id=9%3A362

### **Tasks da funcionalidade**
- [ ] Criar campo de texto para tarefa;
- [ ] Criar campo de data para data;
- [ ] Criar campo de texto para responsável;
- [ ] Criar campo de texto para adicionar mais informações;
- [ ] Criar botão de cancelar e confirmar(não é necessário estar funcionando)
### **Critérios de Aceitação**
- [ ] Estar de acordo com o protótipo;
- [ ] Ser possível voltar para a página anterior;
- [ ] Se conectar com o botão de detalhar da issue #29 .
