### ISSUE TITLE
Criar barra superior na página inicial

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#4]
## **Descrição da nova funcionalidade**
Criar barra superior que fica na página inicial
### **Print da tela do Protótipo**
![Home](https://user-images.githubusercontent.com/46005310/67400248-c53ad980-f583-11e9-944b-76d04fd99d1c.png)

### **Rota da api**
Não precisa

### **Tasks da funcionalidade**
- [ ] Pegar ícone da Orc'estra;
- [ ] Criar barra superior.

### **Critérios de Aceitação**
- [ ] Posicionar itens de acordo com o protótipo;
- [ ] Utilizar identidade visual do protótipo(fonte e cores).
