### ISSUE TITLE
Adicionar Áreas de Trabalho na Tela Inicial

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#5]
## **Descrição da nova funcionalidade**
Adicionar o campo áreas de trabalho na tela inicial,
### Tela
![Home](https://user-images.githubusercontent.com/46005310/67400969-d0423980-f584-11e9-9725-41db42cbf659.png)
### Funcionalidade
![Área de trabalho](https://user-images.githubusercontent.com/46005310/67400991-d801de00-f584-11e9-9a53-02bf00b7e22a.png)

### **Rota da api**
```
http://api.podio.com/org/{org_id}/space
```
Documentação em: https://developers.podio.com/doc/organizations/get-spaces-on-organization-22387

### **Tasks da funcionalidade**
- [ ] Utilizar api para pegar as áreas de trabalho;
- [ ] Filtrar para pegar apenas os dados desejados;
- [ ] Mostrar áreas de trabalho no aplicativo;
- [ ] Mostrar membros que fazem parte daquela área de trabalho.

### **Critérios de Aceitação**
- [ ] Ter conseguido pegar todas as áreas de trabalho;
- [ ] Ter conseguido mostrar as áreas de trabalho no aplicativo.
