### ISSUE TITLE
Criar área de favoritos na tela inicial

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#6]
## **Descrição da nova funcionalidade**
Criar área de favoritos na tela inicial, permitindo que o usuário defina alguma(s) área(s) de trabalho como favorita(s).

#### Tela
![Home](https://user-images.githubusercontent.com/46005310/67402181-96723280-f586-11e9-93b2-dbbfe5b38236.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=2%3A4
#### Funcionalidade
![Favoritos](https://user-images.githubusercontent.com/46005310/67402431-f537ac00-f586-11e9-9e03-af295646219c.png)
Link da funcionalidade: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=2%3A4

### **Rota da api**
```
Área de trabalhos na organização: http://api.podio.com/org/{org_id}/space
Membros na área de trabalho: http://api.podio.com/space/{space_id}/member/
```
Documentação em: https://developers.podio.com/doc/organizations/get-spaces-on-organization-22387 e https://developers.podio.com/doc/space-members/get-members-of-space-22395

### **Tasks da funcionalidade**
- [ ] Criar área de favoritos;
- [ ] Permitir o usuário adicionar uma área aos favoritos.
### **Critérios de Aceitação**
- [ ] Posicionamento de acordo com o protótipo;
- [ ] Seguir mesmo padrão de exibição que o utilizado nas **áreas de trabalho**.
