### ISSUE TITLE
Criar Ordenação na Tela Inicial

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#7]
## **Descrição da nova funcionalidade**
Criar ordenação na tela inicial, sendo que pode ser ordenado por nome da área de trabalho e por última modificação.

#### Tela inicial
![Home](https://user-images.githubusercontent.com/46005310/67403625-95da9b80-f588-11e9-8599-87ac1657c352.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=2%3A4
#### Botão de ordenação
![Ordenar](https://user-images.githubusercontent.com/46005310/67403778-d0dccf00-f588-11e9-8d97-076bec4c9185.png)
Link do botão: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=2%3A4
#### Tela de ordenação
![Ordenação](https://user-images.githubusercontent.com/46005310/67403818-dcc89100-f588-11e9-8a9e-31df2f6d3251.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A410

### **Rota da api**
```
```
### **Tasks da funcionalidade**
- [ ] Criar botão de ordenação;
- [ ] Fazer ordenação alfabética;
- [ ] Fazer ordenação por data de modificação.

### **Critérios de Aceitação**
- [ ] Ordenação funcionando.
