### ISSUE TITLE
Criar esqueleto da tela de atividades

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#8]
## **Descrição da nova funcionalidade**
Criar esqueleto da tela onde serão mostradas todas as atividades feitas no aplicativo.

#### Tela
![Atividades](https://user-images.githubusercontent.com/54643355/67619017-d4609800-f7cc-11e9-9ebe-0a088656bb21.png)

Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A217
#### Funcionalidade
![Barra topo](https://user-images.githubusercontent.com/54643355/67619019-d62a5b80-f7cc-11e9-916a-40f0100ca174.png)

Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A217
### **Rota da api**
Não é necessário
### **Tasks da funcionalidade**
- [x] Criar tela inicial vazia;
- [x] Pegar ícone da Orc'estra;
- [x] Criar barra superior.

### **Critérios de Aceitação**
- [ ] Posicionar itens de acordo com o protótipo;
- [ ] Utilizar identidade visual do protótipo(fonte e cores).
