### ISSUE TITLE
Criar esqueleto da tela de tarefas

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/portalOrcApp#9]
## **Descrição da nova funcionalidade**
Criar esqueleto da tela onde ficarão as tarefas.

#### Tela de tarefas
![minhas-tarefas](https://user-images.githubusercontent.com/54643355/67499327-4f07a700-f657-11e9-9d2c-68b305c3241e.png)
Link da tela: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A524
##### Funcionalidade
![Barra topo-1](https://user-images.githubusercontent.com/54643355/67499419-7199c000-f657-11e9-9be0-8b4b316608e8.png)
Link da funcionalidade: https://www.figma.com/file/FkTBd5HOIVw9ZzRyFGwXZz/Untitled?node-id=5%3A524

### **Rota da api**
Não é necessário

### **Tasks da funcionalidade**
- [x] Criar tela inicial vazia;
- [x] Pegar ícone da Orc'estra;
- [x] Criar barra superior.

### **Critérios de Aceitação**
- [x] Posicionar itens de acordo com o protótipo;
- [x] Utilizar identidade visual do protótipo(fonte e cores).
